import { expect, test, type Locator, type Page } from "@playwright/test";
const EMAIL = "admin@gestman365.local"; const PASSWORD = "admin"; const STORAGE = "gestman365.demo.work-orders.empresa-demo"; const INVALID = /\b(?:NaN|undefined|null|Infinity)\b/i;
async function login(page: Page) { await page.goto("./#/login"); await page.getByLabel("E-mail", { exact: true }).fill(EMAIL); await page.getByLabel("Senha", { exact: true }).fill(PASSWORD); await page.getByRole("button", { name: "Entrar", exact: true }).click(); }
async function openOrders(page: Page) { await login(page); await page.getByRole("link", { name: "Ordens de Servico", exact: true }).click(); await expect(page).toHaveURL(/#\/ordens-servico$/); await expect(page.getByText(/Carregando Ordens/)).toHaveCount(0); }
async function details(page: Page, number: string) { await page.getByRole("button", { name: `Ver detalhes de ${number}` }).click(); return page.getByRole("dialog"); }
async function role(page: Page, selectedRole: "SUPERVISOR" | "PLANEJADOR" | "TECNICO" | "SOLICITANTE") { await page.addInitScript(value => localStorage.setItem("gestman365.react.auth", JSON.stringify({ id: "demo-admin", name: `Perfil ${value}`, email: "admin@gestman365.local", role: value, empresaId: "empresa-demo", isActive: true })), selectedRole); await page.goto("./#/ordens-servico"); await expect(page.getByRole("heading", { name: /Ordens de Servi/ }).first()).toBeVisible(); }
async function fill(dialog: Locator, suffix: string, asset = true) { await dialog.getByRole("textbox", { name: "Título", exact: true }).fill(`Serviço industrial ${suffix}`); await dialog.getByRole("textbox", { name: "Descrição", exact: true }).fill(`Descrição técnica completa do serviço industrial ${suffix}.`); if (asset) await dialog.getByRole("combobox", { name: /Ativo relacionado/ }).selectOption("qa-auto-ativo-mot-001"); else await dialog.getByRole("combobox", { name: /^Setor/ }).selectOption({ label: "Utilidades" }); }

test.describe("GestMan365 - Ordens de Servico", () => {
  test("bloqueia acesso sem autenticacao", async ({ page }) => { await page.goto("./#/ordens-servico"); await expect(page).toHaveURL(/#\/login$/); });
  test("exibe backlog deterministico e estrutura principal", async ({ page }) => { await openOrders(page); await expect(page.getByRole("region", { name: /Filtros de Ordens/ })).toBeVisible(); for (let i = 1; i <= 5; i++) await expect(page.getByText(`QA-AUTO-OS-00${i}`, { exact: true })).toBeVisible(); await expect(page.getByText("5 de 5 O.S.", { exact: true })).toBeVisible(); await expect(page.locator("body")).not.toContainText(INVALID); });
  test("mostra estado vazio", async ({ page }) => { await openOrders(page); await page.getByPlaceholder(/Buscar por n.mero/).fill("OS-INEXISTENTE"); await expect(page.getByText(/Nenhuma Ordem de Servi.*encontrada/)).toBeVisible(); });
  test("busca por numero e titulo", async ({ page }) => { await openOrders(page); const search = page.getByPlaceholder(/Buscar por n.mero/); await search.fill("QA-AUTO-OS-002"); await expect(page.getByText("QA-AUTO-OS-002", { exact: true })).toBeVisible(); await search.fill("compressor"); await expect(page.getByText("QA-AUTO-OS-003", { exact: true })).toBeVisible(); });
  test("filtra status prioridade tipo ativo e tecnico", async ({ page }) => { await openOrders(page); const filters = page.getByRole("region", { name: /Filtros de Ordens/ }); await filters.getByLabel("Status").selectOption("EM_ANALISE"); await expect(page.getByText("QA-AUTO-OS-002", { exact: true })).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Prioridade").selectOption("CRITICA"); await expect(page.getByText("QA-AUTO-OS-003", { exact: true })).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Tipo").selectOption("PREVENTIVA"); await expect(page.getByText("QA-AUTO-OS-004", { exact: true })).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Ativo").selectOption("qa-auto-ativo-cmp-001"); await expect(page.getByText("QA-AUTO-OS-003", { exact: true })).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Técnico").selectOption({ label: "Técnico QA" }); await expect(page.getByText(/2 de 5 O.S/)).toBeVisible(); });
  test("cria O.S. manual vinculada ao ativo", async ({ page }) => { await openOrders(page); await page.getByRole("button", { name: "Nova O.S." }).click(); const dialog = page.getByRole("dialog", { name: /Nova Ordem/ }); await fill(dialog, "manual"); await dialog.getByRole("button", { name: "Criar O.S." }).click(); await expect(page.getByRole("status")).toContainText("QA-AUTO-OS-006"); const detail = await details(page, "QA-AUTO-OS-006"); await expect(detail.getByText(/QA-AUTO-ATIVO-MOT-001/)).toBeVisible(); });
  test("cria servico geral sem ativo quando setor existe", async ({ page }) => { await openOrders(page); await page.getByRole("button", { name: "Nova O.S." }).click(); const dialog = page.getByRole("dialog", { name: /Nova Ordem/ }); await fill(dialog, "geral", false); await dialog.getByRole("button", { name: "Criar O.S." }).click(); const detail = await details(page, "QA-AUTO-OS-006"); await expect(detail.getByText("Serviço geral sem ativo", { exact: true })).toBeVisible(); });
  test("valida titulo descricao e setor obrigatorios", async ({ page }) => { await openOrders(page); await page.getByRole("button", { name: "Nova O.S." }).click(); const dialog = page.getByRole("dialog", { name: /Nova Ordem/ }); await dialog.getByRole("button", { name: "Criar O.S." }).click(); expect(await dialog.getByRole("textbox", { name: "Título", exact: true }).evaluate((el: HTMLInputElement) => el.validity.valueMissing)).toBe(true); expect(await dialog.getByRole("textbox", { name: "Descrição", exact: true }).evaluate((el: HTMLTextAreaElement) => el.validity.valueMissing)).toBe(true); });
  test("gera numeros unicos e persiste durante a sessao", async ({ page }) => { await openOrders(page); for (const name of ["A", "B"]) { await page.getByRole("button", { name: "Nova O.S." }).click(); const dialog = page.getByRole("dialog", { name: /Nova Ordem/ }); await fill(dialog, name); await dialog.getByRole("button", { name: "Criar O.S." }).click(); } await page.reload(); await expect(page.getByText("QA-AUTO-OS-006", { exact: true })).toBeVisible(); await expect(page.getByText("QA-AUTO-OS-007", { exact: true })).toBeVisible(); });
  test("mostra detalhes, origem, ativo e historico", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-001"); await expect(dialog.getByText("QA-AUTO-SOL-001", { exact: true })).toBeVisible(); await expect(dialog.getByRole("region", { name: /Hist.rico/ })).toBeVisible(); await expect(dialog.getByText(/O.S. criada pelo conjunto/)).toBeVisible(); });
  test("edita apenas antes do planejamento", async ({ page }) => { await openOrders(page); let dialog = await details(page, "QA-AUTO-OS-001"); await dialog.getByRole("button", { name: "Editar O.S." }).click(); const form = page.getByRole("dialog", { name: /Editar Ordem/ }); await form.getByRole("textbox", { name: "Título", exact: true }).fill("Motor revisado no planejamento QA"); await form.getByRole("button", { name: /Salvar altera/ }).click(); await expect(page.getByText("Motor revisado no planejamento QA", { exact: true })).toBeVisible(); dialog = await details(page, "QA-AUTO-OS-003"); await expect(dialog.getByRole("button", { name: "Editar O.S." })).toHaveCount(0); });
  test("executa ciclo completo com planejamento, atribuicao e encerramento", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-001"); await dialog.getByRole("button", { name: /Enviar para an.lise/ }).click(); await dialog.getByRole("button", { name: "Planejar O.S." }).click(); await dialog.getByLabel(/Dura.*estimada/).fill("90"); await dialog.getByRole("button", { name: "Salvar planejamento" }).click(); await dialog.getByRole("button", { name: "Atribuir técnico" }).click(); await dialog.getByRole("button", { name: /Confirmar atribui/ }).click(); await dialog.getByRole("button", { name: /Iniciar execu/ }).click(); await dialog.getByRole("button", { name: /Registrar execu/ }).click(); await dialog.getByLabel(/Ação executada/).fill("Substituído rolamento e realizado alinhamento."); await dialog.getByLabel(/Tempo trabalhado/).fill("75"); await dialog.getByLabel(/Tempo de parada/).fill("45"); await dialog.getByRole("button", { name: "Salvar apontamento" }).click(); await dialog.getByRole("button", { name: /Concluir tecnicamente/ }).click(); await expect(dialog.getByText("Concluída", { exact: true })).toBeVisible(); await dialog.getByRole("button", { name: "Encerrar O.S." }).click(); await expect(dialog.getByText("Encerrada", { exact: true })).toBeVisible(); await expect(dialog.getByText(/Encerrada administrativamente|encerrada administrativamente/i)).toBeVisible(); });
  test("pausa exige motivo e permite retomada", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-005"); await dialog.getByRole("button", { name: "Pausar", exact: true }).click(); await dialog.getByRole("button", { name: "Confirmar", exact: true }).click(); await expect(dialog.getByRole("alert")).toContainText(/motivo da pausa/); await dialog.getByLabel(/^Motivo/).fill("Aguardando liberação da área."); await dialog.getByRole("button", { name: "Confirmar", exact: true }).click(); await expect(dialog.getByText("Pausada", { exact: true })).toBeVisible(); await dialog.getByRole("button", { name: /Retomar execu/ }).click(); await expect(dialog.getByText("Em execução", { exact: true })).toBeVisible(); });
  test("bloqueia conclusao sem apontamento tecnico minimo", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-005"); await dialog.getByRole("button", { name: /Concluir tecnicamente/ }).click(); await expect(dialog.getByRole("alert")).toContainText(/ação executada e o tempo trabalhado/); await expect(dialog.getByText("Em execução", { exact: true })).toBeVisible(); });
  test("bloqueia valores negativos no apontamento", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-005"); await dialog.getByRole("button", { name: /Registrar execu/ }).click(); const minutes = dialog.getByLabel(/Tempo trabalhado/); await minutes.fill("-1"); await dialog.getByRole("button", { name: "Salvar apontamento" }).click(); expect(await minutes.evaluate((el: HTMLInputElement) => el.validity.rangeUnderflow)).toBe(true); });
  test("registra espera por material e libera para atribuicao", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-003"); await dialog.getByRole("button", { name: /Aguardar material/ }).click(); await expect(dialog.getByText("Aguardando material", { exact: true })).toBeVisible(); await dialog.getByRole("button", { name: /Liberar e atribuir/ }).click(); await dialog.getByRole("button", { name: /Confirmar atribui/ }).click(); await expect(dialog.getByText("Atribuída", { exact: true })).toBeVisible(); });
  test("cancelamento exige motivo e preserva historico", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-002"); await dialog.getByRole("button", { name: "Cancelar O.S." }).click(); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.getByRole("alert")).toContainText(/motivo do cancelamento/); await dialog.getByLabel(/^Motivo/).fill("Serviço duplicado confirmado."); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.getByText("Cancelada", { exact: true })).toBeVisible(); await expect(dialog.getByText("Serviço duplicado confirmado.", { exact: true })).toBeVisible(); await expect(dialog.getByText(/O.S. cancelada: Serviço duplicado/)).toBeVisible(); });
  test("converte solicitacao aprovada uma unica vez e cria vinculo bidirecional", async ({ page }) => { await login(page); await page.getByRole("link", { name: /Solicitacoes/ }).click(); await page.getByRole("button", { name: "Ver detalhes de QA-AUTO-SOL-003" }).click(); const request = page.getByRole("dialog"); await request.getByRole("button", { name: /Gerar Ordem/ }).click(); await expect(request.getByText(/O.S. criada e vinculada/)).toBeVisible(); await request.getByRole("button", { name: /Fechar detalhes/ }).click(); await page.getByRole("link", { name: "Ordens de Servico" }).click(); await expect(page.getByText("QA-AUTO-OS-006", { exact: true })).toBeVisible(); const order = await details(page, "QA-AUTO-OS-006"); await expect(order.getByText("QA-AUTO-SOL-003", { exact: true })).toBeVisible(); const stored = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key) ?? "[]"), STORAGE); expect(stored.filter((item: { requestId?: string }) => item.requestId === "qa-auto-sol-003")).toHaveLength(1); });
  test("nao oferece conversao para solicitacao nao aprovada", async ({ page }) => { await login(page); await page.getByRole("link", { name: /Solicitacoes/ }).click(); await page.getByRole("button", { name: "Ver detalhes de QA-AUTO-SOL-001" }).click(); await expect(page.getByRole("button", { name: /Gerar Ordem/ })).toHaveCount(0); });
  test("reabertura controlada exige justificativa", async ({ page }) => { await openOrders(page); const dialog = await details(page, "QA-AUTO-OS-004"); await dialog.getByRole("button", { name: /Iniciar execu/ }).click(); await dialog.getByRole("button", { name: /Registrar execu/ }).click(); await dialog.getByLabel(/Ação executada/).fill("Inspeção executada sem anomalias."); await dialog.getByLabel(/Tempo trabalhado/).fill("30"); await dialog.getByRole("button", { name: /Salvar apontamento/ }).click(); await dialog.getByRole("button", { name: /Concluir tecnicamente/ }).click(); await dialog.getByRole("button", { name: /Reabrir O.S/ }).click(); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.getByRole("alert")).toContainText(/motivo da reabertura/); await dialog.getByLabel(/^Motivo/).fill("Necessária inspeção complementar."); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.getByText("Planejada", { exact: true })).toBeVisible(); });
  test("Tecnico ve somente O.S. atribuidas e nao planeja nem encerra", async ({ page }) => { await role(page, "TECNICO"); await expect(page.getByText(/2 de 2 O.S/)).toBeVisible(); await expect(page.getByRole("button", { name: "Nova O.S." })).toHaveCount(0); const dialog = await details(page, "QA-AUTO-OS-004"); await expect(dialog.getByRole("button", { name: /Iniciar execu/ })).toBeVisible(); await expect(dialog.getByRole("button", { name: /Planejar|Cancelar|Encerrar/ })).toHaveCount(0); });
  test("Planejador cria e planeja sem executar ou encerrar", async ({ page }) => { await role(page, "PLANEJADOR"); await expect(page.getByRole("button", { name: "Nova O.S." })).toBeVisible(); let dialog = await details(page, "QA-AUTO-OS-002"); await expect(dialog.getByRole("button", { name: /Planejar O.S/ })).toBeVisible(); await dialog.getByRole("button", { name: /Fechar detalhes/ }).click(); dialog = await details(page, "QA-AUTO-OS-004"); await expect(dialog.getByRole("button", { name: /Iniciar execu/ })).toHaveCount(0); });
  test("Solicitante acompanha apenas O.S. de sua origem", async ({ page }) => { await role(page, "SOLICITANTE"); await expect(page.getByText(/1 de 1 O.S/)).toBeVisible(); await expect(page.getByText("QA-AUTO-OS-001", { exact: true })).toBeVisible(); await expect(page.getByText("QA-AUTO-OS-002", { exact: true })).toHaveCount(0); await expect(page.getByRole("button", { name: "Nova O.S." })).toHaveCount(0); });
  test("Supervisor planeja executa e encerra sem limpar QA ou cancelar", async ({ page }) => { await role(page, "SUPERVISOR"); await expect(page.getByRole("button", { name: "Nova O.S." })).toBeVisible(); await expect(page.getByRole("button", { name: /Limpar dados QA/ })).toHaveCount(0); const dialog = await details(page, "QA-AUTO-OS-002"); await expect(dialog.getByRole("button", { name: /Planejar O.S/ })).toBeVisible(); await expect(dialog.getByRole("button", { name: /Cancelar O.S/ })).toHaveCount(0); });
  test("isola empresa mesmo diante de registro contaminado", async ({ page }) => { await openOrders(page); await page.evaluate(key => { const rows = JSON.parse(sessionStorage.getItem(key) ?? "[]"); rows.push({ ...rows[0], id: "foreign", number: "QA-FOREIGN-OS", empresaId: "outra-empresa" }); sessionStorage.setItem(key, JSON.stringify(rows)); }, STORAGE); await page.reload(); await expect(page.getByText("QA-FOREIGN-OS", { exact: true })).toHaveCount(0); await expect(page.getByText(/5 de 5 O.S/)).toBeVisible(); });
  test("limpa somente QA-AUTO-OS e preserva registro operacional", async ({ page }) => { await openOrders(page); await page.evaluate(key => { const rows = JSON.parse(sessionStorage.getItem(key) ?? "[]"); rows.push({ ...rows[0], id: "legacy", number: "OS-LEGADO-001", title: "Registro preservado" }); sessionStorage.setItem(key, JSON.stringify(rows)); }, STORAGE); await page.reload(); page.once("dialog", value => value.accept()); await page.getByRole("button", { name: /Limpar dados QA/ }).click(); await expect(page.getByText("OS-LEGADO-001", { exact: true })).toBeVisible(); await expect(page.getByText("QA-AUTO-OS-001", { exact: true })).toHaveCount(0); });
  test("nao gera erros de console ou rede", async ({ page }) => { const errors: string[] = []; const failed: string[] = []; page.on("pageerror", error => errors.push(error.message)); page.on("console", entry => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("requestfailed", request => failed.push(request.url())); await openOrders(page); await expect(page.getByRole("heading", { name: /Backlog de Ordens/ })).toBeVisible(); expect(errors).toEqual([]); expect(failed).toEqual([]); });
  test("abre cadastro por teclado com foco no titulo", async ({ page }) => { await openOrders(page); const button = page.getByRole("button", { name: "Nova O.S." }); await button.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("textbox", { name: "Título", exact: true })).toBeFocused(); });
  for (const viewport of [{ name: "desktop", width: 1920, height: 1080 }, { name: "tablet", width: 768, height: 1024 }, { name: "celular", width: 390, height: 844 }]) test(`permanece responsivo em ${viewport.name}`, async ({ page }) => { await page.setViewportSize({ width: viewport.width, height: viewport.height }); await openOrders(page); await expect(page.getByRole("button", { name: "Nova O.S." })).toBeVisible(); await expect(page.getByRole("button", { name: "Ver detalhes de QA-AUTO-OS-001" })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
});
