import { expect, test, type Locator, type Page } from "@playwright/test";
const EMAIL = "admin@gestman365.local"; const PASSWORD = "admin"; const PCM_STORAGE = "gestman365.demo.pcm.empresa-demo"; const OS_STORAGE = "gestman365.demo.work-orders.empresa-demo"; const INVALID = /\b(?:NaN|undefined|null|Infinity)\b/i;
async function login(page: Page) { await page.goto("./#/login"); await page.getByLabel("E-mail", { exact: true }).fill(EMAIL); await page.getByLabel("Senha", { exact: true }).fill(PASSWORD); await page.getByRole("button", { name: "Entrar", exact: true }).click(); }
async function openPcm(page: Page) { await login(page); await page.getByRole("link", { name: "PCM", exact: true }).click(); await expect(page).toHaveURL(/#\/pcm$/); await expect(page.getByText("Carregando planos...")).toHaveCount(0); }
async function details(page: Page, code: string) { await page.getByRole("button", { name: `Ver detalhes de ${code}` }).click(); return page.getByRole("dialog"); }
async function role(page: Page, selectedRole: "SUPERVISOR" | "PLANEJADOR" | "TECNICO" | "SOLICITANTE") { await page.addInitScript(value => localStorage.setItem("gestman365.react.auth", JSON.stringify({ id: "demo-admin", name: `Perfil ${value}`, email: "admin@gestman365.local", role: value, empresaId: "empresa-demo", isActive: true })), selectedRole); await page.goto("./#/pcm"); }
async function fillPlan(dialog: Locator, code = "QA-AUTO-PCM-TST-001") { await dialog.getByLabel("Código do plano").fill(code); await dialog.getByLabel("Ativo relacionado").selectOption("qa-auto-ativo-mot-001"); await dialog.getByLabel("Nome do plano").fill("Plano preventivo automatizado"); await dialog.getByLabel("Descrição").fill("Inspeção preventiva completa criada pela automação QA."); await dialog.getByLabel("Procedimento").fill("Bloquear o ativo, inspecionar e registrar resultados."); }

test.describe("GestMan365 - PCM e manutencao preventiva", () => {
  test("bloqueia acesso sem autenticacao", async ({ page }) => { await page.goto("./#/pcm"); await expect(page).toHaveURL(/#\/login$/); });
  test("exibe estrutura, indicadores sem valores artificiais e quatro planos", async ({ page }) => { await openPcm(page); await expect(page.getByRole("heading", { name: "PCM e Manutenção Preventiva" })).toBeVisible(); await expect(page.getByRole("region", { name: "Resumo do PCM" })).toContainText("Estrutura base"); await expect(page.getByText("4 de 4 plano(s)")).toBeVisible(); const list = page.getByRole("region", { name: "Planos e programação" }); for (const code of ["QA-AUTO-PCM-MOT-001", "QA-AUTO-PCM-BOM-001", "QA-AUTO-PCM-CMP-001", "QA-AUTO-PCM-INS-001"]) await expect(list.getByText(code, { exact: true })).toBeVisible(); await expect(page.locator("body")).not.toContainText(INVALID); });
  test("mostra estado vazio", async ({ page }) => { await openPcm(page); await page.getByPlaceholder("Buscar por código, nome ou descrição").fill("PCM-INEXISTENTE"); await expect(page.getByText("Nenhum plano encontrado para os filtros informados.")).toBeVisible(); });
  test("busca por codigo e nome", async ({ page }) => { await openPcm(page); const search = page.getByPlaceholder("Buscar por código, nome ou descrição"); const list = page.getByRole("region", { name: "Planos e programação" }); await search.fill("QA-AUTO-PCM-BOM-001"); await expect(page.getByText("1 de 4 plano(s)")).toBeVisible(); await search.fill("compressor"); await expect(list.getByText("QA-AUTO-PCM-CMP-001", { exact: true })).toBeVisible(); });
  test("filtra status, gatilho e ativo", async ({ page }) => { await openPcm(page); const filters = page.getByRole("region", { name: "Filtros de planos de manutenção" }); const list = page.getByRole("region", { name: "Planos e programação" }); await filters.getByLabel("Status").selectOption("ATIVO"); await expect(page.getByText("4 de 4 plano(s)")).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Gatilho").selectOption("HORIMETRO"); await expect(list.getByText("QA-AUTO-PCM-CMP-001", { exact: true })).toBeVisible(); await filters.getByRole("button", { name: "Limpar filtros" }).click(); await filters.getByLabel("Ativo do plano").selectOption("qa-auto-ativo-bom-001"); await expect(list.getByText("QA-AUTO-PCM-BOM-001", { exact: true })).toBeVisible(); });
  test("calendario mostra programacao dos planos ativos", async ({ page }) => { await openPcm(page); const calendar = page.getByRole("region", { name: "Programação preventiva" }); await expect(calendar.getByText("QA-AUTO-PCM-MOT-001", { exact: true })).toBeVisible(); await expect(calendar.getByText("QA-AUTO-PCM-INS-001", { exact: true })).toBeVisible(); });
  test("cria plano em rascunho vinculado ao ativo", async ({ page }) => { await openPcm(page); await page.getByRole("button", { name: "Novo plano" }).click(); const dialog = page.getByRole("dialog", { name: "Novo plano de manutenção" }); await fillPlan(dialog); await dialog.getByRole("button", { name: "Criar plano" }).click(); await expect(page.getByRole("status")).toContainText("Plano criado em rascunho"); await expect(page.getByText("QA-AUTO-PCM-TST-001", { exact: true })).toBeVisible(); const detail = await details(page, "QA-AUTO-PCM-TST-001"); await expect(detail.getByText("QA-AUTO-ATIVO-MOT-001", { exact: true })).toBeVisible(); await expect(detail.getByText("Rascunho", { exact: true })).toBeVisible(); });
  test("valida campos obrigatorios", async ({ page }) => { await openPcm(page); await page.getByRole("button", { name: "Novo plano" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByRole("button", { name: "Criar plano" }).click(); expect(await dialog.getByLabel("Ativo relacionado").evaluate((el: HTMLSelectElement) => el.validity.valueMissing)).toBe(true); });
  test("exige prefixo QA no modo demo", async ({ page }) => { await openPcm(page); await page.getByRole("button", { name: "Novo plano" }).click(); const dialog = page.getByRole("dialog"); await fillPlan(dialog, "PLANO-SEM-PREFIXO"); await dialog.getByRole("button", { name: "Criar plano" }).click(); await expect(dialog.getByRole("alert")).toContainText("use o prefixo QA-AUTO-PCM"); });
  test("bloqueia codigo duplicado", async ({ page }) => { await openPcm(page); await page.getByRole("button", { name: "Novo plano" }).click(); const dialog = page.getByRole("dialog"); await fillPlan(dialog, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Criar plano" }).click(); await expect(dialog.getByRole("alert")).toContainText("Já existe um plano"); });
  test("bloqueia frequencia menor que um", async ({ page }) => { await openPcm(page); await page.getByRole("button", { name: "Novo plano" }).click(); const dialog = page.getByRole("dialog"); await fillPlan(dialog); const frequency = dialog.getByLabel("Frequência"); await frequency.fill("0"); await dialog.getByRole("button", { name: "Criar plano" }).click(); expect(await frequency.evaluate((el: HTMLInputElement) => el.validity.rangeUnderflow)).toBe(true); });
  test("detalhes exibem procedimento, versao e historico", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await expect(dialog.getByText(/Inspecionar ruído, vibração/)).toBeVisible(); await expect(dialog.getByRole("region", { name: "Histórico do plano" })).toContainText("Plano ativado"); });
  test("edicao de periodicidade incrementa versao", async ({ page }) => { await openPcm(page); let dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Editar plano" }).click(); const form = page.getByRole("dialog", { name: "Editar plano de manutenção" }); await form.getByLabel("Frequência").fill("2"); await form.getByRole("button", { name: "Salvar alterações" }).click(); dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await expect(dialog.getByText("2", { exact: true })).toBeVisible(); await expect(dialog.getByText(/nova versão de periodicidade/)).toBeVisible(); });
  test("suspensao exige motivo", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Suspender" }).click(); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.getByRole("alert")).toContainText("motivo da suspensão"); });
  test("suspende e reativa mantendo rastreabilidade", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Suspender" }).click(); await dialog.getByLabel("Motivo da suspensão").fill("Janela de produção indisponível."); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(dialog.locator(".work-order-status")).toHaveText("Suspenso"); await expect(dialog.getByRole("button", { name: "Gerar O.S." })).toHaveCount(0); await dialog.getByRole("button", { name: "Reativar plano" }).click(); await expect(dialog.locator(".work-order-status")).toHaveText("Ativo"); await expect(dialog.getByText(/Plano reativado/)).toBeVisible(); });
  test("gera O.S. preventiva e cria vinculo bidirecional", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Gerar O.S." }).click(); await expect(page.getByRole("status")).toContainText(/gerada e vinculada/); const orders = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key) ?? "[]"), OS_STORAGE); const generated = orders.find((item: { maintenancePlanCode?: string }) => item.maintenancePlanCode === "QA-AUTO-PCM-MOT-001"); expect(generated).toMatchObject({ maintenancePlanId: "qa-auto-pcm-mot-001", maintenanceCompetence: "2026-08-01", status: "PLANEJADA" }); const plans = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key) ?? "[]"), PCM_STORAGE); expect(plans.find((item: { id: string }) => item.id === "qa-auto-pcm-mot-001").generatedWorkOrderIds).toContain(generated.id); });
  test("geracao repetida para mesma competencia e idempotente", async ({ page }) => { await openPcm(page); let dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Gerar O.S." }).click(); await dialog.getByRole("button", { name: "Fechar detalhes do plano" }).click(); await page.evaluate(key => { const rows = JSON.parse(sessionStorage.getItem(key) ?? "[]"); const plan = rows.find((item: { id: string }) => item.id === "qa-auto-pcm-mot-001"); plan.nextExecution = "2026-08-01"; sessionStorage.setItem(key, JSON.stringify(rows)); }, PCM_STORAGE); await page.reload(); dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Gerar O.S." }).click(); await expect(page.getByRole("status")).toContainText("nenhuma duplicidade"); const count = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key) ?? "[]").filter((item: { maintenancePlanId?: string; maintenanceCompetence?: string }) => item.maintenancePlanId === "qa-auto-pcm-mot-001" && item.maintenanceCompetence === "2026-08-01").length, OS_STORAGE); expect(count).toBe(1); });
  test("horimetro bloqueia leitura regressiva", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-CMP-001"); await dialog.getByRole("button", { name: "Registrar leitura" }).click(); const input = dialog.getByLabel("Nova leitura"); await input.fill("2400"); await dialog.getByRole("button", { name: "Confirmar" }).click(); expect(await input.evaluate((el: HTMLInputElement) => el.validity.rangeUnderflow)).toBe(true); });
  test("horimetro aceita avanco positivo e registra historico", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-CMP-001"); await dialog.getByRole("button", { name: "Registrar leitura" }).click(); await dialog.getByLabel("Nova leitura").fill("2600"); await dialog.getByRole("button", { name: "Confirmar" }).click(); await expect(page.getByRole("status")).toContainText("Leitura registrada"); await expect(dialog.getByText("Leitura atualizada para 2600.", { exact: true })).toBeVisible(); });
  test("arquiva sem excluir historico e impede novas acoes", async ({ page }) => { await openPcm(page); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await dialog.getByRole("button", { name: "Arquivar" }).click(); await expect(dialog.getByText("Arquivado", { exact: true })).toBeVisible(); await expect(dialog.getByText(/Plano arquivado com histórico preservado/)).toBeVisible(); await expect(dialog.getByRole("button", { name: /Gerar O.S.|Editar plano|Arquivar/ })).toHaveCount(0); });
  test("planejador cria e edita, mas nao arquiva nem gera", async ({ page }) => { await role(page, "PLANEJADOR"); await expect(page.getByRole("heading", { name: "PCM e Manutenção Preventiva" })).toBeVisible(); await expect(page.getByRole("button", { name: "Novo plano" })).toBeVisible(); const dialog = await details(page, "QA-AUTO-PCM-MOT-001"); await expect(dialog.getByRole("button", { name: "Editar plano" })).toBeVisible(); await expect(dialog.getByRole("button", { name: /Arquivar|Gerar O.S.|Suspender/ })).toHaveCount(0); });
  test("tecnico nao acessa administracao de planos", async ({ page }) => { await role(page, "TECNICO"); await expect(page).toHaveURL(/#\/403$/); });
  test("isola registros de outra empresa", async ({ page }) => { await openPcm(page); await page.evaluate(key => { const rows = JSON.parse(sessionStorage.getItem(key) ?? "[]"); rows.push({ ...rows[0], id: "foreign-pcm", code: "QA-FOREIGN-PCM", empresaId: "outra-empresa" }); sessionStorage.setItem(key, JSON.stringify(rows)); }, PCM_STORAGE); await page.reload(); await expect(page.getByText("QA-FOREIGN-PCM", { exact: true })).toHaveCount(0); await expect(page.getByText("4 de 4 plano(s)")).toBeVisible(); });
  test("limpeza remove somente QA-AUTO-PCM", async ({ page }) => { await openPcm(page); await page.evaluate(key => { const rows = JSON.parse(sessionStorage.getItem(key) ?? "[]"); rows.push({ ...rows[0], id: "operacional", code: "PLANO-OPERACIONAL-001" }); sessionStorage.setItem(key, JSON.stringify(rows)); }, PCM_STORAGE); await page.reload(); page.once("dialog", value => value.accept()); await page.getByRole("button", { name: "Limpar dados QA" }).click(); const list = page.getByRole("region", { name: "Planos e programação" }); await expect(list.getByText("PLANO-OPERACIONAL-001", { exact: true })).toBeVisible(); await expect(page.getByText("QA-AUTO-PCM-MOT-001", { exact: true })).toHaveCount(0); });
  test("nao produz erro de console ou falha critica de rede", async ({ page }) => { const errors: string[] = []; const failed: string[] = []; page.on("pageerror", e => errors.push(e.message)); page.on("console", e => { if (e.type() === "error") errors.push(e.text()); }); page.on("requestfailed", r => failed.push(r.url())); await openPcm(page); await expect(page.getByRole("heading", { name: "Planos e programação" })).toBeVisible(); expect(errors).toEqual([]); expect(failed).toEqual([]); });
  test("abre novo plano por teclado e posiciona foco", async ({ page }) => { await openPcm(page); const button = page.getByRole("button", { name: "Novo plano" }); await button.focus(); await page.keyboard.press("Enter"); await expect(page.getByLabel("Código do plano")).toBeFocused(); });
  for (const viewport of [{ name: "desktop", width: 1920, height: 1080 }, { name: "tablet", width: 768, height: 1024 }, { name: "celular", width: 390, height: 844 }]) test(`permanece responsivo em ${viewport.name}`, async ({ page }) => { await page.setViewportSize({ width: viewport.width, height: viewport.height }); await openPcm(page); await expect(page.getByRole("button", { name: "Novo plano" })).toBeVisible(); await expect(page.getByRole("button", { name: "Ver detalhes de QA-AUTO-PCM-MOT-001" })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
});
