import { expect, test, type Locator, type Page } from "@playwright/test";

const EMAIL = "admin@gestman365.local";
const PASSWORD = "admin";
const INVENTORY_KEY = "gestman365.demo.inventory.empresa-demo";
const OS_KEY = "gestman365.demo.work-orders.empresa-demo";
const INVALID = /\b(?:NaN|undefined|null|Infinity)\b/i;

async function login(page: Page) {
  await page.goto("./#/login");
  if (await page.getByRole("button", { name: "Entrar", exact: true }).isVisible()) {
    await page.getByLabel("E-mail", { exact: true }).fill(EMAIL);
    await page.getByLabel("Senha", { exact: true }).fill(PASSWORD);
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
  }
}

async function openInventory(page: Page) {
  await login(page);
  await page.goto("./#/estoque");
  await expect(page.getByText("Carregando estoque...")).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Estoque, Materiais e Ferramentas" })).toBeVisible();
}

async function move(page: Page, code: string, type: string, quantity: string, reason = "Movimentação automatizada QA", workOrder = "qa-auto-os-003") {
  await page.getByRole("button", { name: `Movimentar ${code}` }).click();
  const dialog = page.getByRole("dialog", { name: `Movimentar ${code}` });
  await dialog.getByLabel("Tipo de movimentação").selectOption(type);
  await dialog.getByLabel(type === "INVENTARIO" ? "Quantidade contada" : "Quantidade").fill(quantity);
  if (["RESERVA", "CANCELAMENTO_RESERVA", "CONSUMO_OS", "DEVOLUCAO_OS"].includes(type)) await dialog.getByLabel("Ordem de Serviço").selectOption(workOrder);
  await dialog.getByLabel("Motivo").fill(reason);
  await dialog.getByRole("button", { name: "Registrar movimentação" }).click();
  return dialog;
}

async function itemRow(page: Page, code: string): Promise<Locator> {
  return page.getByRole("row").filter({ hasText: code });
}

async function useRole(page: Page, role: "SUPERVISOR" | "PLANEJADOR" | "TECNICO" | "SOLICITANTE") {
  await page.addInitScript(value => localStorage.setItem("gestman365.react.auth", JSON.stringify({ id: "demo-admin", name: `Perfil ${value}`, email: "admin@gestman365.local", role: value, empresaId: "empresa-demo", isActive: true })), role);
  await page.goto("./#/estoque");
}

test.describe("GestMan365 - estoque, materiais e ferramentas", () => {
  test("01 protege o módulo sem autenticação", async ({ page }) => { await page.goto("./#/estoque"); await expect(page).toHaveURL(/#\/login$/); });
  test("02 exibe o módulo na navegação do administrador", async ({ page }) => { await login(page); await expect(page.getByRole("link", { name: "Estoque e Materiais", exact: true })).toBeVisible(); });
  test("03 abre a rota oficial do estoque", async ({ page }) => { await openInventory(page); await expect(page).toHaveURL(/#\/estoque$/); });
  test("04 apresenta os quatro indicadores operacionais", async ({ page }) => { await openInventory(page); const summary = page.getByRole("region", { name: "Resumo do estoque" }); for (const text of ["Itens ativos", "Estoque baixo", "Quantidade reservada", "Ferramentas emprestadas"]) await expect(summary.getByText(text, { exact: true })).toBeVisible(); });
  test("05 carrega quatro itens QA controlados", async ({ page }) => { await openInventory(page); await expect(page.getByText("4 de 4 item(ns)")).toBeVisible(); for (const code of ["QA-AUTO-EST-ROL-6205", "QA-AUTO-EST-COR-A42", "QA-AUTO-EST-OLEO-ISO68", "QA-AUTO-EST-FILTRO-001"]) await expect(page.getByText(code, { exact: true })).toBeVisible(); });
  test("06 mostra saldo total reservado e disponível", async ({ page }) => { await openInventory(page); const row = await itemRow(page, "QA-AUTO-EST-ROL-6205"); await expect(row).toContainText("20 UN"); await expect(row).toContainText("0 UN"); });
  test("07 busca item pelo código", async ({ page }) => { await openInventory(page); await page.getByPlaceholder("Buscar por código, descrição, categoria ou local").fill("QA-AUTO-EST-COR-A42"); await expect(page.getByText("1 de 4 item(ns)")).toBeVisible(); });
  test("08 busca item pela descrição", async ({ page }) => { await openInventory(page); await page.getByPlaceholder("Buscar por código, descrição, categoria ou local").fill("lubrificante"); await expect(page.getByText("QA-AUTO-EST-OLEO-ISO68", { exact: true })).toBeVisible(); });
  test("09 filtra por categoria", async ({ page }) => { await openInventory(page); await page.getByLabel("Categoria").selectOption("Rolamentos"); await expect(page.getByText("1 de 4 item(ns)")).toBeVisible(); });
  test("10 filtra estoque baixo sem inventar alertas", async ({ page }) => { await openInventory(page); await page.getByLabel("Somente estoque baixo").check(); await expect(page.getByText("Nenhum item encontrado para os filtros informados.")).toBeVisible(); });
  test("11 limpa todos os filtros", async ({ page }) => { await openInventory(page); await page.getByPlaceholder("Buscar por código, descrição, categoria ou local").fill("correia"); await page.getByRole("button", { name: "Limpar filtros" }).click(); await expect(page.getByText("4 de 4 item(ns)")).toBeVisible(); });
  test("12 exibe estado vazio de busca", async ({ page }) => { await openInventory(page); await page.getByPlaceholder("Buscar por código, descrição, categoria ou local").fill("ITEM-INEXISTENTE"); await expect(page.getByText("Nenhum item encontrado para os filtros informados.")).toBeVisible(); });
  test("13 abre cadastro com foco no código", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Novo item" }).click(); await expect(page.getByLabel("Código")).toBeFocused(); });
  test("14 valida campos obrigatórios do item", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Novo item" }).click(); const dialog = page.getByRole("dialog", { name: "Novo item de estoque" }); await dialog.getByLabel("Código").fill(""); await dialog.getByRole("button", { name: "Salvar item" }).click(); expect(await dialog.getByLabel("Código").evaluate((el: HTMLInputElement) => el.validity.valueMissing)).toBe(true); });
  test("15 exige prefixo QA-AUTO-EST", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Novo item" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Código").fill("ITEM-001"); await dialog.getByLabel("Descrição").fill("Item de teste"); await dialog.getByLabel("Categoria").fill("Teste"); await dialog.getByLabel("Localização padrão").fill("T-01"); await dialog.getByRole("button", { name: "Salvar item" }).click(); await expect(dialog.getByRole("alert")).toContainText("QA-AUTO-EST"); });
  test("16 bloqueia código duplicado", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Novo item" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Código").fill("QA-AUTO-EST-ROL-6205"); await dialog.getByLabel("Descrição").fill("Item duplicado"); await dialog.getByLabel("Categoria").fill("Teste"); await dialog.getByLabel("Localização padrão").fill("T-01"); await dialog.getByRole("button", { name: "Salvar item" }).click(); await expect(dialog.getByRole("alert")).toContainText("Já existe um item"); });
  test("17 cria item sem alterar saldo automaticamente", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Novo item" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Código").fill("QA-AUTO-EST-TST-001"); await dialog.getByLabel("Descrição").fill("Item automatizado"); await dialog.getByLabel("Categoria").fill("Testes"); await dialog.getByLabel("Localização padrão").fill("T-01"); await dialog.getByRole("button", { name: "Salvar item" }).click(); await expect(page.getByRole("status")).toContainText("Item criado"); const row = await itemRow(page, "QA-AUTO-EST-TST-001"); await expect(row).toContainText("0 UN"); });
  test("18 edita metadados sem reescrever histórico", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Editar QA-AUTO-EST-COR-A42" }).click(); const dialog = page.getByRole("dialog", { name: "Editar item de estoque" }); await dialog.getByLabel("Localização padrão").fill("A-09-09"); await dialog.getByRole("button", { name: "Salvar item" }).click(); await expect(await itemRow(page, "QA-AUTO-EST-COR-A42")).toContainText("A-09-09"); });
  test("19 registra entrada e atualiza saldo", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-ROL-6205", "ENTRADA", "2"); await expect(page.getByRole("status")).toContainText("Entrada registrada"); await expect(await itemRow(page, "QA-AUTO-EST-ROL-6205")).toContainText("22 UN"); });
  test("20 registra saída com saldo disponível", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "SAIDA", "2"); await expect(await itemRow(page, "QA-AUTO-EST-COR-A42")).toContainText("8 UN"); });
  test("21 bloqueia saída acima do saldo disponível", async ({ page }) => { await openInventory(page); const dialog = await move(page, "QA-AUTO-EST-COR-A42", "SAIDA", "999"); await expect(dialog.getByRole("alert")).toContainText("Saldo disponível insuficiente"); });
  test("22 exige quantidade positiva", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Quantidade").fill("0"); await dialog.getByLabel("Motivo").fill("Teste"); await dialog.getByRole("button", { name: "Registrar movimentação" }).click(); expect(await dialog.getByLabel("Quantidade").evaluate((el: HTMLInputElement) => el.validity.rangeUnderflow)).toBe(true); });
  test("23 exige motivo da movimentação", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByRole("button", { name: "Registrar movimentação" }).click(); expect(await dialog.getByLabel("Motivo").evaluate((el: HTMLTextAreaElement) => el.validity.valueMissing)).toBe(true); });
  test("24 reserva material para O.S.", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-ROL-6205", "RESERVA", "3"); const row = await itemRow(page, "QA-AUTO-EST-ROL-6205"); await expect(row).toContainText("3 UN"); await expect(row).toContainText("17 UN"); });
  test("25 bloqueia reserva acima do saldo", async ({ page }) => { await openInventory(page); const dialog = await move(page, "QA-AUTO-EST-ROL-6205", "RESERVA", "30"); await expect(dialog.getByRole("alert")).toContainText("Saldo disponível insuficiente"); });
  test("26 cancela reserva existente", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-ROL-6205", "RESERVA", "3"); await move(page, "QA-AUTO-EST-ROL-6205", "CANCELAMENTO_RESERVA", "2"); await expect(await itemRow(page, "QA-AUTO-EST-ROL-6205")).toContainText("1 UN"); });
  test("27 bloqueia cancelamento maior que a reserva", async ({ page }) => { await openInventory(page); const dialog = await move(page, "QA-AUTO-EST-ROL-6205", "CANCELAMENTO_RESERVA", "1"); await expect(dialog.getByRole("alert")).toContainText("supera a reserva"); });
  test("28 registra consumo vinculado à O.S.", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-OLEO-ISO68", "CONSUMO_OS", "5"); await expect(await itemRow(page, "QA-AUTO-EST-OLEO-ISO68")).toContainText("45 L"); });
  test("29 devolve material consumido na O.S.", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-OLEO-ISO68", "CONSUMO_OS", "5"); await move(page, "QA-AUTO-EST-OLEO-ISO68", "DEVOLUCAO_OS", "2"); await expect(await itemRow(page, "QA-AUTO-EST-OLEO-ISO68")).toContainText("47 L"); });
  test("30 bloqueia devolução acima do consumo", async ({ page }) => { await openInventory(page); const dialog = await move(page, "QA-AUTO-EST-OLEO-ISO68", "DEVOLUCAO_OS", "1"); await expect(dialog.getByRole("alert")).toContainText("não pode superar o consumo"); });
  test("31 registra ajuste positivo com justificativa", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "AJUSTE_POSITIVO", "1", "Contagem física aprovada"); await expect(await itemRow(page, "QA-AUTO-EST-COR-A42")).toContainText("11 UN"); });
  test("32 registra ajuste negativo sem saldo negativo", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "AJUSTE_NEGATIVO", "1", "Avaria confirmada"); await expect(await itemRow(page, "QA-AUTO-EST-COR-A42")).toContainText("9 UN"); });
  test("33 realiza inventário pela quantidade contada", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "INVENTARIO", "12", "Inventário rotativo"); await expect(await itemRow(page, "QA-AUTO-EST-COR-A42")).toContainText("12 UN"); });
  test("34 valida origem e destino da transferência", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Tipo de movimentação").selectOption("TRANSFERENCIA"); await dialog.getByLabel("Destino").fill("A-02-03"); await dialog.getByLabel("Motivo").fill("Transferência de teste"); await dialog.getByRole("button", { name: "Registrar movimentação" }).click(); await expect(dialog.getByRole("alert")).toContainText("origem e destino diferentes"); });
  test("35 inativa item sem apagar cadastro", async ({ page }) => { await openInventory(page); page.once("dialog", dialog => dialog.accept()); await page.getByRole("button", { name: "Inativar QA-AUTO-EST-FILTRO-001" }).click(); await expect(await itemRow(page, "QA-AUTO-EST-FILTRO-001")).toContainText("Inativo"); });
  test("36 preserva histórico imutável de movimentações", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "ENTRADA", "1"); await page.getByRole("tab", { name: "Movimentações" }).click(); const history = page.getByRole("region", { name: "Histórico de movimentações" }); await expect(history).toContainText("Saldo inicial controlado"); await expect(history).toContainText("Movimentação automatizada QA"); });
  test("37 calcula custo total apenas quando há custo médio", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-ROL-6205", "SAIDA", "2"); await page.getByRole("tab", { name: "Movimentações" }).click(); await expect(page.getByRole("region", { name: "Histórico de movimentações" })).toContainText("R$ 97,00"); });
  test("38 não inventa custo ausente", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-FILTRO-001", "SAIDA", "1"); await page.getByRole("tab", { name: "Movimentações" }).click(); await expect(page.getByRole("region", { name: "Histórico de movimentações" })).toContainText("Não informado"); });
  test("39 replica reserva no histórico da O.S.", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-ROL-6205", "RESERVA", "2"); await page.goto("./#/ordens-servico"); await page.getByRole("button", { name: "Ver detalhes de QA-AUTO-OS-003" }).click(); const dialog = page.getByRole("dialog"); await expect(dialog.getByRole("region", { name: "Materiais da Ordem de Serviço" })).toContainText("Rolamento 6205 ZZ"); await expect(dialog.getByRole("region", { name: "Histórico da Ordem de Serviço" })).toContainText("RESERVA"); });
  test("40 replica consumo e custo realizado na O.S.", async ({ page }) => { await openInventory(page); await move(page, "QA-AUTO-EST-COR-A42", "CONSUMO_OS", "2"); await page.goto("./#/ordens-servico"); await page.getByRole("button", { name: "Ver detalhes de QA-AUTO-OS-003" }).click(); const materials = page.getByRole("region", { name: "Materiais da Ordem de Serviço" }); await expect(materials).toContainText("Correia A42"); await expect(materials).toContainText("R$ 64,00"); });
  test("41 não oferece O.S. encerrada ou cancelada", async ({ page }) => { await openInventory(page); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Tipo de movimentação").selectOption("RESERVA"); await expect(dialog.getByLabel("Ordem de Serviço").locator("option[value='closed-order']")).toHaveCount(0); });
  test("42 PCM mantém materiais previstos sem baixar saldo", async ({ page }) => { await openInventory(page); const before = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key)!).items.find((item: { code: string }) => item.code === "QA-AUTO-EST-ROL-6205").quantityTotal, INVENTORY_KEY); await page.goto("./#/pcm"); await page.getByRole("button", { name: "Ver detalhes de QA-AUTO-PCM-MOT-001" }).click(); await page.getByRole("dialog").getByRole("button", { name: "Gerar O.S." }).click(); const after = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key)!).items.find((item: { code: string }) => item.code === "QA-AUTO-EST-ROL-6205").quantityTotal, INVENTORY_KEY); expect(after).toBe(before); const orders = await page.evaluate(key => JSON.parse(sessionStorage.getItem(key) ?? "[]"), OS_KEY); expect(orders.find((order: { maintenancePlanCode?: string }) => order.maintenancePlanCode === "QA-AUTO-PCM-MOT-001").plannedMaterials[0].inventoryItemId).toBe("qa-auto-est-rol-6205"); });
  test("43 lista ferramenta controlada QA", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await expect(page.getByText("QA-AUTO-FERR-001", { exact: true })).toBeVisible(); });
  test("44 cria ferramenta disponível", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await page.getByRole("button", { name: "Nova ferramenta" }).click(); const dialog = page.getByRole("dialog", { name: "Nova ferramenta" }); await dialog.getByLabel("Código").fill("QA-AUTO-FERR-TST-001"); await dialog.getByLabel("Descrição").fill("Alicate amperímetro"); await dialog.getByLabel("Condição").fill("Calibrado"); await dialog.getByLabel("Localização").fill("F-02"); await dialog.getByRole("button", { name: "Salvar ferramenta" }).click(); await expect(page.getByText("QA-AUTO-FERR-TST-001", { exact: true })).toBeVisible(); });
  test("45 impede ferramenta duplicada", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await page.getByRole("button", { name: "Nova ferramenta" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Código").fill("QA-AUTO-FERR-001"); await dialog.getByLabel("Descrição").fill("Duplicada"); await dialog.getByLabel("Condição").fill("Boa"); await dialog.getByLabel("Localização").fill("F-02"); await dialog.getByRole("button", { name: "Salvar ferramenta" }).click(); await expect(dialog.getByRole("alert")).toContainText("Já existe uma ferramenta"); });
  test("46 registra empréstimo vinculado à O.S.", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await page.getByRole("button", { name: "Emprestar QA-AUTO-FERR-001" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Responsável").fill("Técnico QA"); await dialog.getByLabel("Previsão de devolução").fill("2026-07-30T16:00"); await dialog.getByLabel("Ordem de Serviço").selectOption("qa-auto-os-003"); await dialog.getByRole("button", { name: "Confirmar empréstimo" }).click(); await expect(page.getByRole("status")).toContainText("Empréstimo registrado"); await expect(page.getByRole("region", { name: "Ferramentas controladas" })).toContainText("QA-AUTO-OS-003"); });
  test("47 impede empréstimo duplicado e sinaliza atraso", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await page.getByRole("button", { name: "Emprestar QA-AUTO-FERR-001" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel("Responsável").fill("Técnico QA"); await dialog.getByLabel("Previsão de devolução").fill("2026-07-20T16:00"); await dialog.getByRole("button", { name: "Confirmar empréstimo" }).click(); await expect(page.getByRole("button", { name: "Emprestar QA-AUTO-FERR-001" })).toHaveCount(0); await expect(page.getByRole("alert")).toHaveText("Devolução atrasada"); });
  test("48 registra devolução e condição", async ({ page }) => { await openInventory(page); await page.getByRole("tab", { name: "Ferramentas" }).click(); await page.getByRole("button", { name: "Emprestar QA-AUTO-FERR-001" }).click(); let dialog = page.getByRole("dialog"); await dialog.getByLabel("Responsável").fill("Técnico QA"); await dialog.getByLabel("Previsão de devolução").fill("2026-07-30T16:00"); await dialog.getByRole("button", { name: "Confirmar empréstimo" }).click(); await page.getByRole("button", { name: "Devolver QA-AUTO-FERR-001" }).click(); dialog = page.getByRole("dialog"); await dialog.getByLabel("Condição na devolução").fill("Sem avarias"); await dialog.getByRole("button", { name: "Confirmar devolução" }).click(); await expect(page.getByRole("region", { name: "Ferramentas controladas" })).toContainText("Sem avarias"); });
  test("49 administrador possui cadastro e movimentações completas", async ({ page }) => { await openInventory(page); await expect(page.getByRole("button", { name: "Novo item" })).toBeVisible(); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); await expect(page.getByLabel("Tipo de movimentação").locator("option")).toHaveCount(12); });
  test("50 supervisor consulta e movimenta sem cadastrar", async ({ page }) => { await useRole(page, "SUPERVISOR"); await expect(page.getByRole("heading", { name: "Estoque, Materiais e Ferramentas" })).toBeVisible(); await expect(page.getByRole("button", { name: "Novo item" })).toHaveCount(0); await expect(page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" })).toBeVisible(); });
  test("51 planejador reserva sem ajustar saldo", async ({ page }) => { await useRole(page, "PLANEJADOR"); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); const options = page.getByLabel("Tipo de movimentação").locator("option"); await expect(options).toHaveCount(2); await expect(page.getByLabel("Tipo de movimentação")).toContainText("Reserva"); });
  test("52 técnico consome e devolve sem editar cadastro", async ({ page }) => { await useRole(page, "TECNICO"); await expect(page.getByRole("button", { name: "Editar QA-AUTO-EST-COR-A42" })).toHaveCount(0); await page.getByRole("button", { name: "Movimentar QA-AUTO-EST-COR-A42" }).click(); await expect(page.getByLabel("Tipo de movimentação").locator("option")).toHaveCount(2); });
  test("53 solicitante não acessa operação de estoque", async ({ page }) => { await useRole(page, "SOLICITANTE"); await expect(page).toHaveURL(/#\/403$/); });
  test("54 isola dados de outra empresa e recupera JSON inválido", async ({ page }) => { await openInventory(page); await page.evaluate(key => { const state = JSON.parse(sessionStorage.getItem(key)!); state.items.push({ ...state.items[0], id: "foreign-item", empresaId: "outra-empresa", code: "QA-FOREIGN-ITEM" }); sessionStorage.setItem(key, JSON.stringify(state)); }, INVENTORY_KEY); await page.reload(); await expect(page.getByText("QA-FOREIGN-ITEM", { exact: true })).toHaveCount(0); await page.evaluate(key => sessionStorage.setItem(key, "{json-invalido"), INVENTORY_KEY); await page.reload(); await expect(page.getByText("4 de 4 item(ns)")).toBeVisible(); });
  test("55 não gera erros de console, rede ou valores inválidos", async ({ page }) => { const errors: string[] = []; const failed: string[] = []; page.on("pageerror", error => errors.push(error.message)); page.on("console", entry => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("requestfailed", request => failed.push(request.url())); await openInventory(page); await expect(page.locator("body")).not.toContainText(INVALID); expect(errors).toEqual([]); expect(failed).toEqual([]); });
  test("56 mantém responsividade em desktop, tablet e celular sem rolagem horizontal", async ({ page }) => {
    for (const viewport of [{ width: 1920, height: 1080 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) {
      await page.setViewportSize(viewport);
      await openInventory(page);
      await expect(page.getByRole("heading", { name: "Estoque, Materiais e Ferramentas" })).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    }
  });
});
