import { useState, type FormEvent } from "react";
import type { Asset } from "@/types/assets";
import { PLAN_STATUS_LABELS, TRIGGER_TYPE_LABELS, type MaintenancePlan } from "@/types/pcm";
export function MaintenancePlanDetailsDialog({ plan, asset, canPlan, canManage, onClose, onEdit, onActivate, onSuspend, onReactivate, onArchive, onGenerate, onMeter }: { plan: MaintenancePlan; asset?: Asset; canPlan: boolean; canManage: boolean; onClose: () => void; onEdit: () => void; onActivate: () => Promise<void>; onSuspend: (reason: string) => Promise<void>; onReactivate: () => Promise<void>; onArchive: () => Promise<void>; onGenerate: () => Promise<void>; onMeter: (value: number) => Promise<void> }) {
  const [mode, setMode] = useState<"SUSPEND" | "METER" | null>(null); const [reason, setReason] = useState(""); const [meter, setMeter] = useState(plan.meterCurrent ?? 0); const [error, setError] = useState("");
  async function run(action: () => Promise<void>) { setError(""); try { await action(); setMode(null); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível concluir."); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (mode === "SUSPEND") await run(() => onSuspend(reason)); else await run(() => onMeter(meter)); }
  return <div className="dialog-backdrop" role="presentation"><section className="dialog-card pcm-details" role="dialog" aria-modal="true" aria-labelledby="pcm-details-title">
    <header className="dialog-header"><div><span className={`work-order-status status-${plan.status.toLowerCase()}`}>{PLAN_STATUS_LABELS[plan.status]}</span><h2 id="pcm-details-title">{plan.code}</h2><p>{plan.name}</p></div><button className="icon-button" type="button" aria-label="Fechar detalhes do plano" onClick={onClose}>×</button></header>
    <div className="details-grid"><div><span>Ativo</span><strong>{asset?.tag ?? "Ativo não encontrado"}</strong></div><div><span>Gatilho</span><strong>{TRIGGER_TYPE_LABELS[plan.triggerType]}</strong></div><div><span>Próxima execução</span><strong>{plan.nextExecution}</strong></div><div><span>Versão</span><strong>{plan.version}</strong></div><div><span>Duração prevista</span><strong>{plan.estimatedDurationMinutes} min</strong></div><div><span>O.S. geradas</span><strong>{plan.generatedWorkOrderIds.length}</strong></div><div className="details-wide"><span>Procedimento</span><strong>{plan.procedure}</strong></div>{plan.suspensionReason ? <div className="details-wide"><span>Motivo da suspensão</span><strong>{plan.suspensionReason}</strong></div> : null}</div>
    {mode ? <form className="inline-action-form" onSubmit={submit}><h3>{mode === "SUSPEND" ? "Suspender plano" : "Registrar leitura"}</h3>{mode === "SUSPEND" ? <label className="form-field-wide">Motivo da suspensão<textarea value={reason} onChange={e => setReason(e.target.value)} rows={3} /></label> : <label className="form-field-wide">Nova leitura<input type="number" min={plan.meterCurrent ?? 0} value={meter} onChange={e => setMeter(Number(e.target.value))} /></label>}<div className="dialog-actions form-field-wide"><button className="btn ghost" type="button" onClick={() => setMode(null)}>Voltar</button><button className="btn primary" type="submit">Confirmar</button></div></form> : null}
    {error ? <div className="error-message" role="alert">{error}</div> : null}
    <section className="work-order-history" aria-label="Histórico do plano"><h3>Histórico e rastreabilidade</h3><ol>{[...plan.history].reverse().map(item => <li key={item.id}><strong>{item.description}</strong><span>{item.actorName} — {new Date(item.at).toLocaleString("pt-BR")}</span></li>)}</ol></section>
    <div className="dialog-actions pcm-actions">{canPlan && plan.status !== "ARQUIVADO" ? <button className="btn ghost" type="button" onClick={onEdit}>Editar plano</button> : null}{canManage && plan.status === "RASCUNHO" ? <button className="btn primary" type="button" onClick={() => void run(onActivate)}>Ativar plano</button> : null}{canManage && plan.status === "ATIVO" ? <><button className="btn ghost" type="button" onClick={() => setMode("SUSPEND")}>Suspender</button><button className="btn primary" type="button" onClick={() => void run(onGenerate)}>Gerar O.S.</button></> : null}{canManage && plan.status === "SUSPENSO" ? <button className="btn primary" type="button" onClick={() => void run(onReactivate)}>Reativar plano</button> : null}{canPlan && ["HORIMETRO", "QUILOMETRAGEM", "CICLOS"].includes(plan.triggerType) && plan.status !== "ARQUIVADO" ? <button className="btn ghost" type="button" onClick={() => setMode("METER")}>Registrar leitura</button> : null}{canManage && plan.status !== "ARQUIVADO" ? <button className="btn danger" type="button" onClick={() => void run(onArchive)}>Arquivar</button> : null}</div>
  </section></div>;
}
